apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-events-to-slack-streamer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-events-to-slack-streamer
rules:
- apiGroups: [""]
  resources: ["events", "pods", "nodes"]
  verbs: ["watch", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-events-to-slack-streamer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-events-to-slack-streamer
subjects:
- kind: ServiceAccount
  name: k8s-events-to-slack-streamer
  namespace: observer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-events-to-slack-streamer
  labels:
    app: k8s-events-to-slack-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-events-to-slack-streamer
  template:
    metadata:
      labels:
        app: k8s-events-to-slack-streamer
    spec:
      automountServiceAccountToken: true
      serviceAccountName: k8s-events-to-slack-streamer
      containers:
      - image: YOUR_IMAGE_IN_DOCKERHUB
        imagePullPolicy: Always
        name: k8s-events-to-slack-streamer
        env:
        - name: K8S_EVENTS_STREAMER_INCOMING_WEB_HOOK_URL
          value: YOUR_SLACK_WEB_HOOK_URL
        - name: K8S_EVENTS_STREAMER_SKIP_DELETE_EVENTS
          value: "true"
        - name: K8S_EVENTS_STREAMER_LIST_OF_REASONS_TO_SKIP
          value: 'Scheduled ScalingReplicaSet Pulling Created Pulled Started SuccessfulMountVolume SuccessfulUnMountVolume SuccessfulCreate'
